# Generated by Django 4.2.4 on 2023-11-25 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_criar_perfil_ong", "0001_initial"),
        ("app_pagina_inicial", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicacao",
            name="autor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publicacoes",
                to="app_criar_perfil_ong.cadastroong",
            ),
        ),
    ]
