# Generated by Django 4.2.5 on 2023-11-29 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_criar_perfil_ong', '0001_initial'),
        ('app_criar_perfil_doador', '0001_initial'),
        ('app_pagina_inicial', '0002_alter_publicacao_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(max_length=20)),
                ('valor', models.BigIntegerField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='app_criar_perfil_doador.cadastro')),
                ('ong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doacoes', to='app_criar_perfil_ong.cadastroong')),
            ],
            options={
                'db_table': 'doacoes',
            },
        ),
    ]
